name = input("please enter your name: ")
print(name)
surname = input("please enter your surname: ")
print(surname)
number =input()
Number =input()
NUMBER =input()
print(number + Number + NUMBER / 3)
str = (5)
Str = (5)
print(str * 5)
print(Str * 5)
num1 = input()
num2 = input()
print(num1 + num2)
print(int(num1) - int(num2))
print(num1 * int(num2))
print(int(num1) / int(num2))